name: Test

on:
  push:
    branches:
      - dev

jobs:
  test_frontend:
    name: 'Format & Build Frontend'
    runs-on: ubuntu-latest
    continue-on-error: false  # This ensures the workflow fails if this step fails
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Or specify any other version you want to use

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: npm install

      - name: Run i18next
        run: npm run i18n:parse

      - name: Build Frontend
        run: npm run build

  test_release:
    runs-on: ubuntu-latest
    needs: [test_frontend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version number from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "::set-output name=version::$VERSION"

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      - name: Clean npm cache
        id: clean_cache
        run: npm cache clean --force
        
      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.clean_cache.conclusion == 'success'
