name: Test
permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'
      - '*.md'

jobs:
  test_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version number from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "::set-output name=version::$VERSION"

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Clean npm cache
        id: clean_cache
        run: npm cache clean --force

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build --wheel --verbose .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.clean_cache.conclusion == 'success'
